<?php
//white_domain_list
//白名單機制...，白名單是
//@date 2018年12月23日
//value=-1,代表失效本條規則，暫只支持單網域名稱（針對引入外部白名單時的精確控制）,當處於strict_mode時，排除此key，單條關閉strict_mode
//value=0,代表僅加白單條網域名稱
//value=1,代表其下級網域名稱全部加白（例如3級網域名稱，則其4級子網域名稱全部加白）
//value=2,代表僅加白主網域名稱及其子網域名稱，即如果是主網域名稱，加白全部，如果是子網域名稱，加白命中的單條
// Formatter: https://www.duplichecker.com/php-formatter

return [
    "cdn-thumb.fds.api.xiaomi.com" => 0,
    "bce.baidu.com" => 0,
    "b.bdstatic.com" => 0,
    "goatcounter.com" => 0,
    "pornimg.xyz" => 0,
    "etracker.com" => 0,
    "etracker.de" => 0,
    "edge.activity.windows.com" => 0,
    "edge-enterprise.activity.windows.com" => 0,
    "imasdk.googleapis.com" => 0,
    "gss0.bdstatic.com" => 0, //百度貼吧頭像
    "googleadapis.l.google.com" => 0, //解決google字體下載異常
    "gstaticadssl.l.google.com" => 0, //解決google字體下載異常
    //"gvt2.com" => 1, //gvt2，安卓系統相關, #558
    "wangbase.com" => 1, //阮一峰同志的部落格圖片顯示
    "l.qq.com" => 0, //解決騰訊視頻無法播放
    "dldir1.qq.com" => 0, //qq下載安裝包路徑
    "cgi.connect.qq.com" => 0, //qq互聯
    "stdl.qq.com" => 0, //qq瀏覽器
    "wup.imtt.qq.com" => 0, //qq瀏覽器書籤
    "pacaio.match.qq.com" => 0, //騰訊網qq登錄
    "gia.jd.com" => 0, //京東滑動驗證碼
    "edge.yunjiasu.com" => 0, //百度雲加速javascript快速加載功能
    "cd.bendibao.com" => 0, //成都本地寶
    "m.qpic.cn" => 0, // qq，微信，QQ空間等用到的靜態資源網域名稱
    "ipify.org" => 1, // 獲得公網 IP
    "pass.1688.com" => 0, // 阿里巴巴網站訪問不正常
    "cedexis.net" => 0, // windowsupdate CNAME
    "y0.cn" => 0, // 短網址服務，涉及本次丁香醫生實時疫情頁面 http://y0.cn/sari
    "click.taobao.com" => 0, //淘寶粉絲福利購
    "t1.baidu.com" => 0, //百度圖片自有平台
    "t2.baidu.com" => 0, //百度圖片自有平台
    "t3.baidu.com" => 0, //百度圖片自有平台
    "t4.baidu.com" => 0, //百度圖片自有平台
    "t5.baidu.com" => 0, //百度圖片自有平台
    "t6.baidu.com" => 0, //百度圖片自有平台
    "t7.baidu.com" => 0, //百度圖片自有平台
    "t8.baidu.com" => 0, //百度圖片自有平台
    "t9.baidu.com" => 0, //百度圖片自有平台
    "t10.baidu.com" => 0, //百度圖片自有平台
    "t11.baidu.com" => 0, //百度圖片自有平台
    "t12.baidu.com" => 0, //百度圖片自有平台
    "bytedance.com" => 0, //字節跳動
    "tbskip.taobao.com" => 1, //淘寶訂單搜尋相關
    "wl.jd.com" => 0, //修復京東pc首頁加載異常
    "tanx.com" => 0, //餓了麼店舖異常
    "promotion.aliyun.com" => 0, //阿里雲控制台
    "rarbg.to" => 0, //BT站
    "rarbgprx.org" => 0, //BT站
    "rarbgmirror.org" => 0, //BT站
    "rarbgmirror.com" => 0, //BT站
    "rarbgmirrored.org" => 0, //BT站
    "rarbgaccess.org" => 0, //BT站
    "rarbgp2p.org" => 0, //BT站
    "rarbgproxied.org" => 0, //BT站
    "rarbgproxy.org" => 0, //BT站
    "rarbgto.org" => 0, //BT站
    "rarbgway.org" => 0, //BT站
    "rarbg2019.org" => 0, //BT站
    "rarbg2020.org" => 0, //BT站
    "rarbg2021.org" => 0, //BT站
    "gsp0.baidu.com" => 0, //百度貼吧相關
    "gsp1.baidu.com" => 0, //百度貼吧相關
    "gsp2.baidu.com" => 0, //百度貼吧相關
    "gsp3.baidu.com" => 0, //百度貼吧相關
    "sp0.baidu.com" => 0, //百度翻譯資源
    "sp2.baidu.com" => 0, //百度翻譯資源
    "c0.ifengimg.com" => 0, //鳳凰網視頻異常
    "7moor.com" => 0, //山姆會員客服異常
    "v.smtcdns.net" => 0, //影響部分B站直播
    "gameone.com" => 0, //影響部分B站直播
    "ultraiso.net" => 1, //軟碟通官網
    "mmstat.com" => 0, //修復優酷視頻顯示禁用了cookie
    "log.mmstat.com" => 0, //修復優酷視頻顯示禁用了cookie
    "adm.10jqka.com.cn" => 0, //修復同花順的tips異常
    "cps.kaola.com" => 0, //考拉的cps，放行
    "iteye.com" => 0, //某編程網站
    "dl.360safe.com" => 0, //360驅動下載
    "resolver.msg.xiaomi.net" => 0, //小愛音箱語音識別
    "api.sec.miui.com" => 0, //miui自帶騷擾攔截相關
    "iface2.iqiyi.com" => 0, //愛奇藝 相關視頻推薦
    "apm3.music.163.com" => 0, //網易雲音樂
    "mbd.baidu.com" => 0, //百度百家號
    "suo.im" => 0, //短網址服務
    "hinet.net" => 0,
    "hubpd.com" => 0, //黨媒平台網址
    "i.niupic.com" => 0, //免費圖床地址
    "api-game.meizu.com" => 0, //魅族商店更新遊戲
    "image.uczzd.cn" => 0, //uc頭條的圖片 #67
    "dg.k.jd.com" => 0, //京東不能跳轉app
    "orbit.jd.com" => 0, //京東不能跳轉app
    "kepler.jd.com" => 0, //京東不能跳轉app
    "widget.weibo.com" => 0, //微博誤殺
    "sailthru.com" => 0, //誤殺epicgame.com，因CNAME #73
    "t1.58cdn.com.cn" => 0, // 58同城cdn #75
    "t2.58cdn.com.cn" => 0, // 58同城cdn #75
    "t3.58cdn.com.cn" => 0, // 58同城cdn #75
    "ddns.net" => 0, // #76
    "pushbullet.com" => 0, // #77
    "now.sh" => 0, // #78
    "zimuku.la" => 0, // #84
    "qihucdn.com" => 0, // #89
    "sqimg.qq.com" => 0, // #90
    "haohuo.snssdk.com" => 0, // 抖音訂單列表
    "acs.m.taobao.com" => 0, // #92
    "perfops.net" => 0, // #96
    "msg.video.qiyi.com" => 0, // #93
    "img.zuoyebang.cc" => 0, // 作業幫拍照搜題
    "data.video.iqiyi.com" => 0, // 愛奇藝電視投屏
    "cp81.ott.cibntv.net" => 0, // CIBN雲視聽異常 #107
    "sj.uukanshu.com" => 0, // 誤殺 #110
    "e.shifen.com" => 0, // 百度的某個cname網域名稱，誤殺嚴重
    "gvt1.com" => 0, // google play #117
    "apiwz.midukanshu.com" => 0, // #120
    "api.jr.mi.com" => 0, // #121
    "graph.facebook.com" => 0,
    "image.box.xiaomi.com" => 0, // #124
    "niuza.com" => 1, // #124
    "sourl.cn" => 0, // #123
    "pp.ua" => 0, // #131
    "search.video.iqiyi.com" => 0, // #132
    "wanproxy.127.net" => 0, // #137
    "shouji.360.cn" => 0, // #136
    "ae01.alicdn.com" => 0, // #142
    // 'pingjs.qq.com' => 0, // #143
    "shifen.com" => 0, // 百度的cname
    "f10.baidu.com" => 0, // 百度公眾號圖片
    "f11.baidu.com" => 0, // 百度公眾號圖片
    "f12.baidu.com" => 0, // 百度公眾號圖片
    "bj.bcebos.com" => 0, // 百度雲產品
    "kingsoft.com" => 0, // 金山軟件
    "top.baidu.com" => 0, // 百度風雲榜
    "aiseet.atianqi.com" => 0, // #147
    "data.bilibili.com" => 0, // #148
    "get3.adobe.com" => 0, // #152
    "ex.qq.com" => 0, // #153
    "1sapp.com" => 0, // #156
    "dyn.ithome.com" => 0, // #157
    "sf6-ttcdn-tos.pstatp.com" => 0, // #159
    "api.tv.sohu.com" => 0, // 搜狐視頻win app版不能使用
    "ip2location.com" => 0, // #163
    "livere.com" => 0, // #170
    "ucan.25pp.com" => 0, // #171
    "privateinternetaccess.com" => 0, // #174
    "shopify.com" => 0, // #179
    "co.in" => 0, //https://github.com/nextdns/metadata/issues/364
    "91mobiles.com" => 0, // #215
    "m.1234567.com.cn" => 0, // #213
    "woniu.com" => 0, // #227
    "du.163.com" => 0, // #229
    "zaloapp.com" => 0, // #230
    "manhuachi.com" => 0, // #238
    "push2.eastmoney.com" => 0, // #239
    "slashdot.org" => 0, // #242
    "iwx.mail.qq.com" => 0, // #243
    "ename.net" => 0, // #246
    "api.iplay.163.com" => 0, // #247
    "minorshort.weixin.qq.com" => 0, // 微信滑動驗證碼
    "pusher.com" => 0, // #248
    "bluehost.com" => 0, // #249
    "hosting24.com" => 0, // #252
    "pdc.micloud.xiaomi.net" => 0, // #256
    "valf.atm.cp31.ott.cibntv.net" => 0, // #257
    "sf1-ttcdn-tos.pstatp.com" => 0, // #258
    "sf3-ttcdn-tos.pstatp.com" => 0, // #258
    "upload.cc" => 0, // #262
    "yql.yahoo.com" => 0, // #263
    "naifei.shop" => 0, // #267
    "tagtic.cn" => 0, // #266
    "settings-win.data.microsoft.com" => 0, // #268
    "db5-eap.settings-win.data.microsoft.com.akadns.net" => 0, // #268
    "db5.settings-win.data.microsoft.com.akadns.net" => 0, // #268
    "geo.settings-win.data.microsoft.com.akadns.net" => 0, // #268
    "printfriendly.com" => 0, // #272
    "cnnic.cn" => 0, #274
    "ss.cnnic.cn" => 0, #274
    "www.cnnic.cn" => 0, #274
    "cnnic.net" => 0, #274
    "www.cnnic.net" => 0, #274
    "cnnic.net.cn" => 0, #274
    "www.cnnic.net.cn" => 0, #274
    "c.gj.qq.com" => 0, #273
    "isee.weishi.qq.com" => 0, #270
    "direct.wap.zol.com.cn" => 0, #275
    "imop.com" => 0, #283
    "mobilelog.kugou.com" => 0, #286
    "bssdlbig.kugou.com" => 0, #286
    "tvzhe.com" => 0, #290
    "stats.gc.apple.com" => 0, #296
    "img1.sj.qq.com" => 0, #294
    "live.simcitybuildit.com" => 0, #303
    "subscription.iqiyi.com" => 0, #306
    "azureedge.net" => 0, #309
    "surge.sh" => 0, // qq group, @frank
    "ccclub.cmbchina.com" => 0, // #313
    "adv.ccb.com" => 0, // #316
    "conac.cn" => 0, // #317
    "mix.sina.com.cn" => 0, // #320
    "jwpcdn.com" => 0, // #322
    "retcode.taobao.com" => 0, // #312
    "3975.com" => 0, // #326
    "air.1688.com" => 0, // #331
    "continuum.dds.microsoft.com" => 0, // #335
    "sec.resource.xiaomi.net" => 0, // #328
    "api.cortana.ai" => 0, // #338
    "mazu.3g.qq.com" => 0, // #340
    "umiwi.com" => 0, // #341
    "xmpush.xiaomi.com" => 0, // #343
    "app.chat.xiaomi.net" => 0, // https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1726
    "doublecklick.net" => 1, // 拼寫錯誤的網域名稱，https://github.com/privacy-protection-tools/anti-AD/pull/347/files
    "issuecdn.baidupcs.com" => 0, // #350
    "duiba.com.cn" => 0, // #352
    "trib.al" => 0, // #357
    "ccmp.eu" => 0, // #365
    "alissl.ucdl.pp.uc.cn" => 0, // #370
    "c3pool.com" => 0, // #371
    "check.ddos-guard.net" => 0, // #388
    "update.avlyun.sec.miui.com" => 0, // #387
    "sugar.zhihu.com" => 0, // #380
    "chtbl.com" => 0, // #390
    "edge-enterprise.activity.windows.com" => 0, // #401
    "edge.activity.windows.com" => 0, // #401
    "hsforms.com" => 0, // #420
    "hsforms.net" => 0, // #420
    "jx.cn" => 0, // #423
    "qualtrics.com" => 0, // #434
    "assets.ckjr001.com" => 0, // #433
    "kpstaticbj.wx.ckjr001.com" => 0, // #433
    "www.supportxmr.com.cdn.cloudflare.net" => 0, // #436
    "www.supportxmr.com" => 0, // #436
    "supportxmr.com" => 0, // #436
    "pool.supportxmr.com" => 0, // #436
    "pool-de.supportxmr.com" => 0, // #436
    "minergate.com" => 0, // #439
    "imagetwist.com" => 0, // #447
    "kanjiantu.com" => 0, // #451
    "www.kanjiantu.com" => 0, // #451
    "cdn.ark.qq.com" => 0, // #461
    "eq.10jqka.com.cn" => 0, // #463
    "stat.10jqka.com.cn" => 0, // #463
    "ozone.10jqka.com.cn" => 0, // #463
    "sogoucdn.com" => 0, // #471
    "gleam.io" => 0, // #472
    "widget.gleamjs.io" => 0, // #472
    "ipapi.co" => 0, // #470
    "ip-adress.com" => 0, // #470
    "ip-api.com" => 0, // #470
    "ipinfodb.com" => 0, // #470
    "ipstack.com" => 0, // #470
    "d10lpsik1i8c69.cloudfront.net" => 0, // #470
    "d1z2jf7jlzjs58.cloudfront.net" => 0, // #470
    "d1zgderxoe1a.cloudfront.net" => 0, // #470
    "d2na2p72vtqyok.cloudfront.net" => 0, // #470
    "d2r1yp2w7bby2u.cloudfront.net" => 0, // #470
    "d2wy8f7a9ursnm.cloudfront.net" => 0, // #470
    "d31qbv1cthcecs.cloudfront.net" => 0, // #470
    "d35u1vg1q28b3w.cloudfront.net" => 0, // #470
    "d3tglifpd8whs6.cloudfront.net" => 0, // #470
    "d3tsytm1wtjqo2.cloudfront.net" => 0, // #470
    "d5nxst8fruw4z.cloudfront.net" => 0, // #470
    "whoami.akamai.net" => 0, // #208
    "insight.rapid7.com" => 0,
    "exchange4media.com" => 0,
    "kaipuyun.cn" => 0, // #479
    "fraudmetrix.cn" => 1, // #480
    "fp.tongdun.net" => 0, // #480
    "kaptcha.com" => 0, // #481
    "dfcfw.com" => 0, // #482
    "msedge.net" => 0, // #478
    "ecard.shenzhentong.com" => 0, // #486
    "minexmr.com" => 0, // #490
    "appdownload.alicdn.com" => 0, // #491
    "zconfig.alibabausercontent.com" => 0, // #495
    "proofpoint.com" => 0, // #497
    "mini.eastday.com" => 0, // #500
    "dftoutiao.com" => 0, // #500
    "dcms.1688.com" => 0, // #499
    "da.mmarket.com" => 0, // #501
    "log-upload.mihoyo.com" => 0, // #502
    "micpn.com" => 0,
    "kqzyfj.com" => 0,
    "flocktory.com" => 0,
    "wl.spotify.com" => 0, // #508
    "s1.wp.com" => 0, // #510
    "lc-cn-n1-shared.com" => 0, // #512
    "instant.page" => 0, // #514
    "jspassport.ssl.qhimg.com" => 0, // #515
    "service.signalr.net" => 0, // #519
    "threatbook.cn" => 0, // #522
    "gofile.io" => -1, // #525
    "err.taobao.com" => 0, // #521
    "boxer.baidu.com" => 0, // #535
    "simplyhired.com" => 0, // #536
    "x6img.com" => 0, // #537
    "p-l.play.aiseet.atianqi.com" => 0, // #538
    "news-l.play.aiseet.atianqi.com" => 0, // #538
    "bitbucket.io" => 0, #503
    "ename.com.cn" => 0, #503
    "baixing.com" => 0, #503
    "aizhigu.com.cn" => 0, #503
    "clarins.com.cn" => 0, #503
    "jav321.com" => 0, #503
    "knet.cn" => 0, #503
    "pepsico.com.cn" => 0, #503
    "s11.cn" => 0, #503
    "snap.com" => 0, #503
    "nejmqianyan.cn" => 0, #503
    "w8.com.cn" => 0, #503
    "watchtimes.com.cn" => 0, #503
    "whhd.gov.cn" => 0, #503
    "xifuquan.com" => 0, #503
    "xj-n-tax.gov.cn" => 0, #503
    "zazhipu.com" => 0, #503
    "ztgame.com" => 0, #503
    "download.db-ip.com" => 0, #AdGuardSDNSFilter #863
    "db-ip.com" => 0, #AdGuardSDNSFilter #863
    "remind.me" => 0, #AdGuardSDNSFilter #875
    "ipdata.co" => 0, #AdGuardSDNSFilter #878
    "fastly-analytics.com" => 0, #AdGuardSDNSFilter #880
    "yximgs.com" => 0, #554
    "cdn.cnbj1.fds.api.mi-img.com" => 0, #556
    "browser.mi-img.com" => 0, #556
    "pic.imgdb.cn" => 0, #565
    "live-trace.bilibili.com" => 0, #561, #517
    "ip-tracker.org" => 0, #AdGuardSDNSFilter #884, #578
    "tollfreeforwarding.com" => 0, #AdGuardSDNSFilter #886
    "coralogix.com" => 0, #AdGuardSDNSFilter #888
    "adcr.naver.com" => 0, #AdGuardSDNSFilter #891
    "is.snssdk.com" => 0, #579
    "down.360safe.com" => 0, #577
    "soup.v.qq.com" => 0, #576
    "live800.com" => 0, #573
    "www.meipian7.cn" => 0, #586
    "creativecommons.org" => 0, #588
    "go.pardot.com" => 0, #569
    "gbfek.dfcfw.com" => 0, #593
    "dfscdn.dfcfw.com" => 0, #593
    "empic.dfcfw.com" => 0, #593
    "wxapp.lvyadx.cn" => 0, #584
    "canyoublockit.com" => 0, #601
    "d.getpocket.com" => 0, #602
    "pdst.fm" => 0, #603
    "licensebuttons.net" => 0, #609
    "wmflabs.org" => 0, #611
    "jsinfo.net" => 0, #613
    "uol.com.br" => 0, #632
    "ntalker.com" => 0, #626
    "shouji.sogou.com" => 1, #623, #822, #952
    "mo.res.wpscdn.cn" => 0, #636
    "qhres2.com" => 0, #638
    "rumble.com" => 0, #639
    "stackpathdns.com" => 0, #645
    "37signals.com" => 0, #647
    "msg.douyu.com" => 0, #649
    "hot.browser.miui.com" => 0, #655
    "linksnappy.com" => 0, #656
    "szlong.weixin.qq.com" => 0, #659
    "metrics.icloud.com" => 0, #661
    "h-adashx.ut.dingtalk.com" => 0, #662
    "adashx.ut.dingtalk.com" => 0, #662
    "sv.aq.qq.com" => 0, #664
    "ctrip.com" => 0, #666
    "nmobi.kuwo.cn" => 0, #665
    "meipian7.cn" => 0, #672
    "govdelivery.com" => 0, #674
    "jimdo.com" => 0, #675
    "as.mgtv.com" => 0, #678
    "gm.mmstat.com" => 0, #680
    "adobe-campaign.com" => 0, #681
    "profile.csdnimg.cn" => 0, #687
    "meitubeauty.meitudata.com" => 0, #688
    "my-material.zone1.meitudata.com" => 0, #688
    "ssl-cdn.static.browser.mi-img.com" => 0, #689
    "db-ip.com" => 0, #699
    "mini2015.qq.com" => 0, #710
    "alimama.com" => 0, #710
    "salon.com" => 0, #711
    "hqq.tv" => 0, #725
    "sfp.safe.baidu.com" => 0, #728
    "sofire.baidu.com" => 0, #728
    "c.youdao.com" => 0, #729
    "wgo.mmstat.com" => 0, #730
    "eroterest.net" => 0, #731
    "button.like.co" => 0, #737
    "urldefense.com" => 0, #741
    "gift.douyucdn.cn" => 0, #745
    "click.redditmail.com" => 0, #753
    "qiyukf.com" => 0, #754
    "short-video.kakamobi.cn" => 0, #758
    "act.vip.iqiyi.com" => 0, #760
    "vaserviece.10jqka.com.cn" => 0, #765
    "mairuan.com" => 0, #772
    "www.mairuan.com" => 0, #772
    "mairuan.com.cn" => 0, #772
    "www.mairuan.com.cn" => 0, #772
    "mairuan.cn" => 0, #772
    "www.mairuan.cn" => 0, #772
    "mairuan.net" => 0, #772
    "www.mairuan.net" => 0, #772
    "chkaja.com" => 0, #774
    "amdc.m.taobao.com" => 0, #778
    "jiagu.360.cn" => 0, #788
    "ldmnq.com" => 0, #787
    "heytapimage.com" => 0, #779, #780
    "fexclick.baidu.com" => 0, #790
    "jango.com" => 0, #797
    "huluxia.com" => 0, #798
    "ucweb.com" => 0, #801
    "yule.sohu.com" => 0, // #802
    "weworkremotely.com" => 0, // #803
    "zoosnet.net" => 0, // #811
    "sqdd.myapp.com" => 0, // #814
    "eco.taobao.com" => 0, // #815
    "loginfra.com" => 0, // #826
    "api-secure.solvemedia.com" => 0, // #827
    "cupfox.app" => 0, // #829
    "ccmeng.com" => 0, // #830
    "api.open.uc.cn" => 0, // #845
    "code.sms.mob.com" => 0, // #855
    "statsig.com" => 0, // #869, #860
    "api.statsig.com" => 0, // #869, #860
    "up.cm.ksmobile.com" => 0, // #880
    "icanhazip.com" => 0, // #899
    "ak-d.tripcdn.com" => 0, // #903
    "v6-adashx.ut.cainiao.com" => 0, // #904
    "vip.cainiaofx.com" => 0, // #904
    "ib.snssdk.com" => 0, // #905
    "audid-api.taobao.com" => 0, // #906
    "m.intl.taobao.com" => 0, // #907
    "ads.cdn.tvb.com" => 0, // #911
    "ads.console.aliyun.com" => 0, // #912
    "deliver.kuwo.cn" => 0, // #917
    "mcdn.bilivideo.cn" => 0, // #918
    "log.snssdk.com" => 0, // #920
    "i.snssdk.com" => 0, // #920
    "mime.baidu.com" => 0, // #923
    "staticsns.cdn.bcebos.com" => 0, // #925
    "oauth-login-drcn.platform.dbankcloud.com" => 0, // #929
    "firebaseinstallations.googleapis.com" => 0, // #931
    "a0.app.xiaomi.com" => 0, // #932
    "https-filtering-check.adtidy.org" => 0, // #937
    "jnn-pa.googleapis.com" => 0, // #940
    "migc.g.mi.com" => 0, // #942
    "clientlog3.music.163.com" => 0, // #954
    "tracker.ai.xiaomi.com" => 0, // #960
    "awstrack.me" => 0, // #467 #964
    "c.paypal.com" => 0, // #965
    "cc.map.qq.com" => 0, // #974
    "pkoplink.com" => 0, // #998
    "r.stripe.com" => 0, // #1033
    "data.vod.itc.cn" => 0, // #1038
    "similarweb.com" => 0, // #1039
    "analytics.meituan.net" => 0, // #1052
    "ads.heytapmobi.com" => 0, // #1054
    "zynga.com" => 0, // #1060
    "zyngaplayersupport.com" => 0, // #1060
    "adukwai.com" => 0, // #1063
    "p1-lm.adukwai.com" => 0, // #1063
    "snowflake.qq.com" => 0, // #1068
    "ac.dun.163.com" => 0, // #1014
    "ac.dun.163yun.com" => 0, // #1014
    "scarf.sh" => 0, // #957, #993, #1076
    "ads.privacy.qq.com" => 0, // #546

    // upstream-white-easylist 中选取的一些应放行域名
    "a1.itc.cn" => 0,
    "adx.yiche.com" => 0,
    "changyan.sohu.com" => 0,
    "ecma.bdimg.com" => 0,
    "gk.sina.cn" => 0,
    "pv.sohu.com" => 0, // #493
    "sax.sina.com.cn" => 0,
    "statcounter.com" => 0,
    "www.statcounter.com" => 0,
    "tf.360.cn" => 0,
    /* upstream-white-easylist 源规则
      @@||a1.itc.cn/pv/js/spv.
      @@||adx.yiche.com/cityindex.ashx
      @@||changyan.sohu.com/debug/cookie?
      @@||ecma.bdimg.com/holmes/*.svg
      @@||gk.sina.cn/v1/gkmatch?
      @@||pv.sohu.com/suv/
      @@||sax.sina.com.cn/video/newimpress?
      @@||statcounter.com/js//fusioncharts.charts.js
      @@||statcounter.com/js/fusioncharts.js
      @@||www.statcounter.com/images/$image,third-party
      @@||tf.360.cn/e/wb?
    */

    "iflow.uczzd.cn" => 0, // uc搞笑段子
    "m.uczzd.cn" => 0, // uc搞笑段子
    "puds.ucweb.com" => 0, // uc小游戏
    "image.zzd.sm.cn" => 0, // uc浏览器
    "herokuapp.com" => -1,
    "netlify.com" => -1,
    "vidoza.net" => -1,
    "nahnoji.cz" => 1,
    "cloudfront.net" => -1,
    "amazonaws.com" => -1,
    "github.io" => -1,
    "blogspot.com" => -1,
    "cdn77.org" => -1,
    "cloudflare.net" => -1,
    "appspot.com" => -1,
    "cpm.cm.kankan.com" => -1, //-1 失效本條規則，保持現狀，即不加白本網域名稱
    "deliver.ifeng.com" => -1, //保留的dead-hosts，為了縮減其子網域名稱
    "ad.xiaomi.com" => -1, //保留的dead-hosts，為了縮減其子網域名稱

    /**notracking 提議加白的一批網域名稱 start**/
    "scribol.com" => 0,
    "tracking.epicgames.com" => 0,
    "logrocket.com" => 0,
    "loggly.com" => 0,
    "om.cbsi.com" => 0,
    "ipinfo.io" => 0,
    "v.shopify.com" => 0,
    "adobedtm.com" => 0,
    "c.evidon.com" => 0,
    "ereg.wip3.adobe.com" => 0,
    "csi.gstatic.com" => 0,
    "g.msn.com" => 0,
    "sascdn.com" => 0,
    "duckdns.org" => 0,
    "prf.hn" => 0,
    "placehold.it" => 0,
    "digg.com" => 0,
    "feedburner.com" => 0,
    "rambler.ru" => 1,
    "jiathis.com" => 0,
    "rs6.net" => 0,
    "com.com" => 0,
    "s0.2mdn.net" => 0,
    "pr0gramm.com" => 0,
    "consent.cmp.oath.com" => 0,
    "s.youtube.com" => 0,
    "purch.com" => 0,
    "fpdownload.macromedia.com" => 0,
    "dynatrace.com" => 0,
    "auditude.com" => 0,
    "app.link" => 0,
    /**notracking 提議加白的一批網域名稱 end**/

    "activate.adobe.com" => 0,
    "ereg.adobe.com" => 0,
    "hlrcv.stage.adobe.com" => 0,
    "lmlicenses.wip4.adobe.com" => 0,
    "na1r.services.adobe.com" => 0,
    "licenses.adobe.com" => 1,
    "alcohol-soft.com" => 1,
    "licenses.ashampoo.com" => 0,
    "bluesoleil.com" => 1,
    "activation.phaseone.com" => 0,
    "corel.com" => 1,
    "dbregistration.cuteftp.com" => 0,
    "cyberlink.com" => 1,
    "activation.easeus.com" => 0,
    "upd.faronicslabs.com" => 0,
    "lumion3d.com" => 1,
    "lumion3d.net" => 1,
    "act2.mediafour.com" => 0,
    "sams.nikonimaging.com" => 0,
    "license.piriform.com" => 0,
    "www.bitsumactivationserver.com" => 0,
    "licensing.tableausoftware.com" => 0,
    "techsmith.com" => 1,
    "binaryage.com" => 1,
    "wisecleaner.com" => 1,
    "d1bl11pgu3tw3h.cloudfront.net" => 0,
    "tv.sohu.com" => 0,
    "3975.com" => 0,
];
